# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.1'
  pod 'HandyJSON', '~> 5.0.1'
  # Pods for swiftproject

  target 'swiftprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftprojectUITests' do
    # Pods for testing
  end

end
