# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.1'
  pod 'HandyJSON', '~> 5.0.1'
  pod 'Kingfisher', '~> 5.0'
  pod 'SnapKit','~> 5.0.0'
  pod 'SwiftyJSON'
  pod 'MJRefresh'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'FMDB'
  pod "ActiveSQLite"
#  pod 'DoraemonKit/Core', '~> 3.0.0', :configurations => ['Debug'] #Required
#  pod 'DoraemonKit/WithGPS', '~> 3.0.0', :configurations => ['Debug'] #Optional
#  pod 'DoraemonKit/WithLoad', '~> 3.0.0', :configurations => ['Debug'] #Optional
  # Pods for swiftproject

  target 'swiftprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftprojectUITests' do
    # Pods for testing
  end

end
